services:
  # Infrastructure layer

  # Discovery service
  eureka-server:
    build:
      context: .
      dockerfile: ./discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - SERVER_PORT=8761
    networks:
      - zenith-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/eureka/apps" ]
      interval: 30s
      timeout: 10s
      retries: 5

  ## DB - data persistence
  postgres:
    image: postgres:15-alpine
    container_name: zenith-db
    environment:
      POSTGRES_USER: zenith_user
      POSTGRES_PASSWORD: zenith_password
      POSTGRES_DB: zenith_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zenith-network

  ## Cache
  redis:
    image: redis:7-alpine
    container_name: zenith-cache
    ports:
      - "6379:6379"
    networks:
      - zenith-network

  ## Kafka - Messaging
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: zenith-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@zenith-kafka:9093
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://zenith-kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - zenith-network

  # Application layer
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_healthy
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    networks:
      - zenith-network

  identity-service:
    build:
      context: .
      dockerfile: ./identity-service/Dockerfile
    container_name: identity-service
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://zenith-db:5432/zenith_db
      - SPRING_DATASOURCE_USERNAME=zenith_user
      - SPRING_DATASOURCE_PASSWORD=zenith_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    networks:
      - zenith-network

  wallet-service:
    build:
      context: .
      dockerfile: ./wallet-service/Dockerfile
    container_name: wallet-service
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://zenith-db:5432/wallet_db
      - SPRING_DATASOURCE_USERNAME=zenith_user
      - SPRING_DATASOURCE_PASSWORD=zentih_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=zenith-kafka:29092
      - SPRING_REDIS_HOST=zenith-cache
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - SPRING_R2DBC_URL=r2dbc:postgresql://zenith-db:5432/zenith_db
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=password
    networks:
      - zenith-network

  transaction-service:
    build:
      context: .
      dockerfile: ./transaction-service/Dockerfile
    container_name: transaction-service
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://zenith-db:5432/zenith_db
      - SPRING_DATASOURCE_USERNAME=zenith_user
      - SPRING_DATASOURCE_PASSWORD=zenith_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    networks:
      - zenith-network

  reconcile-service:
    build:
      context: .
      dockerfile: ./reconcile-service/Dockerfile
    container_name: reconcile-service
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://zenith-db:5432/zenith_db
      - SPRING_DATASOURCE_USERNAME=zenith_user
      - SPRING_DATASOURCE_PASSWORD=zenith_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    networks:
      - zenith-network

# Network layer
networks:
  zenith-network:
    name: zenith-network
    driver: bridge

volumes:
  postgres_data: